import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Head from "next/head";
import "@/styles/reset.scss";
import "@/styles/index.scss";
import styles from "@/styles/layout.module.scss";

const PlusJacartaSans = Plus_Jakarta_Sans({
  variable: "--primary-font",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TicTacToe",
	applicationName: "TicTacToe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${styles.page} ${PlusJacartaSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
